### ISSUE TITLE
[Search for Journey] Journey Search Request

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#12]
**As** any User **I want to** search between created journeys' information **so that** I can find a journey suitable for me to join.

**Mockup**
<img width="356" alt="US_12_Journey_Search" src="https://user-images.githubusercontent.com/81674765/114454542-63d95100-9be3-11eb-9b93-732c2e01626b.png">

<img width="137" alt="US_12_Journey_Search_1" src="https://user-images.githubusercontent.com/81674765/114454643-81a6b600-9be3-11eb-8ee9-a17f7b3d2e36.png">

### Acceptance Criteria
1. User accesses a Search request, by pushing 'Search for Ride' image at Journey homepage  (US[#23](https://github.com/ita-social-projects/Car-Back-End/issues/23)).
2.  Procedure of adding From/To journey points shall be the same as for Ride Creation (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).
3.  Procedure of adding 'Departure time' shall be the same as for Select Date and Time (US[#2](https://github.com/ita-social-projects/Car-Back-End/issues/2)).
4. 'Passengers' dropdown shall contain options '1', '2', '3', '4' seats.
4.1. Option '1' shall be chosen by default.
5. User shall choose Fee mode pushing button 'All' or 'Free' or 'Paid'.
5.1. Button 'All' shall be active by default. 
6. WHEN User pushes Search button, and system found at least one route, system shall transfer User to page with search results (US[#13](https://github.com/ita-social-projects/Car-Back-End/issues/13)).
7. IF system didn't find any available route, the system shall transfer User to page with search results (US[#15](https://github.com/ita-social-projects/Car-Back-End/issues/15)).
8. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)

**Epic link**
Epic #71 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by TetianaLysak** [comment]
Move **"Do you have a baggage with you to transport?"** from 4th screen to next screen because we don’t need any information about baggage on search step (only in request from passenger to driver)
![image](https://user-images.githubusercontent.com/73545111/107758790-10a46880-6d30-11eb-8205-9a6af7517bd7.png)

**Comment by OlenaBobalo** [comment]
@TetianaLysak Done :-)
