### ISSUE TITLE
[Search for Journey] Search Result

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#13]
**As a** User (Passenger) **I want to** see results of a journey search **so that** I could choose route and time convenient for me.

**Mockup**
Picture 1

![image](https://user-images.githubusercontent.com/91271776/140299439-40018ef5-cb0f-40f8-8e5d-aaf0936e1569.png)

Picture 2. Request/Option panel

![image](https://user-images.githubusercontent.com/91271776/140299610-cfb5b05d-f0c9-4117-a8f4-3ff4042510f3.png)

![image](https://user-images.githubusercontent.com/91271776/140299662-8f005bfe-dc88-4c11-83c3-7f14b922275f.png)

https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3283%3A7836

for 2.1.2.
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=4175%3A16222

### Acceptance Criteria
1. User accesses to this screen from Journey Search page (US[#12](https://github.com/ita-social-projects/Car-Back-End/issues/12)), only IF system found at least one route.
2.  On the top of the page, there should be the label 'Search Results' and 2 available active buttons: 'Back' for returning to the previous page and 'Request' (pict. 2) for journey request (for journeys that don't exist during the search phase, but could be created till the needed departure time) (US[#16](https://github.com/ita-social-projects/Car-Back-End/issues/16)).
2.1. WHEN User pushes 'Request', system rolls up request option panel (pic. 2 frame 39) with 2 options: 'With the previous filters' and 'With new filters'.
**For option 'With new filters':**
2.1.1. The system shows the corresponding pop-up message 'You're about to create a ride request with new filters.' with 2 buttons: 'Yes, create' and 'No, go back' (pic.2 frame 36).
2.1.2. IF User pushes 'Yes, create', the system shall open "Create a Ride Request" page with the Map view (US[#16](https://github.com/ita-social-projects/Car-Back-End/issues/16)).
2.1.3. IF User pushes 'No, go back', system returns to search results.
**For option 'With the previous filters':**
2.1.4. IF User chooses 'With the previous filters', system shall create request and inform User with the pop up "Your Ride Request is created".
3. Each found journey should be circled by the line and consist of such information: N&S of journey organizer, SS position, list of stops during the journey, time of the journey, journey fee (free or paid).
3.1. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)
4. WHEN User pushes at chosen journey box, the system shall transfer User to Map page (US#[14](https://github.com/ita-social-projects/Car-Back-End/issues/14)).

**Assumptions & Constraints**
1. System shall sort the route search result by two criteria:
- **time**: system shall show on the top of trips results such results which are in the scope of 2 hours of the chosen time;
- **distance**: system shall show on the top of trips results, such results which are in the scope of 1 km of the chosen To/From points.
- **free of charge** journeys shall be placed on the top of the search results (in the case when User chooses fee "All" during the search).
2. System shall show only journeys with available sitting places.

**Epic link**
Epic #71 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Sydir** [comment]
2.1.4. IF User chooses 'With the previous filters', system shall create request and inform User with the pop up "Your Ride Request is created". - should be implemented.
