### ISSUE TITLE
[Manage Notifications] Event/Notification page

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#130]
**As** any User **I want to** see all notifications about events **so that** could react to changes in time.

**Mockup**
<img width="409" alt="US_6_Events" src="https://user-images.githubusercontent.com/62544149/109798876-f4effc00-7c23-11eb-94cb-70fa1c03801c.png">

Pict 2. Empty page (without any notifications)
<img width="198" alt="US_6_Events_1" src="https://user-images.githubusercontent.com/62544149/110780315-3c523a00-826d-11eb-8c1f-8dc07fa27671.png">

### Acceptance Criteria
1. User accesses to the "Notifications" page from Footer panel (US #23 ).
2. Notifications shall be separated by the lines and are sorted from the newest till the oldest. Newest should be on the top of the page.
3. Each notification in the list shall contain N&S of the sender, a brief description of notification, and time from notification receipt.
3.1. Requirements to the time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)
4. Unread messages should be highlighted by light-blue color.
4.1. System shall filter upcoming notifications, see US #265 .
5. WHEN User pushes any notification, system shall transfer User to the exact notification page.
5.1. IF notification belongs to "Ask to join journey" category, system shall transfer User to page (view mockup on the right) with info added by potential joiner (US #5 ).
6. Notification list:
- __(Name Surname)__ asked to join your journey(US[#5 ])
- __(Name Surname)__approved your application (US[#416 )
- __(Name Surname)__accepted your invitation (US[#419 )
- __(Name Surname)__marketing news
- __(Name Surname)__marketing survey
- __(Name Surname)__canceled the journey  (US[#458  )
- __(Name Surname)__updated journey details (US #502 )
- __(Name Surname)__invites you to join the journey (US[#418 )
- __(Name Surname)__withdrawn from the journey (US[#459 )
- __(Name Surname)__rejected your invitation (US[#419 )
- __(Name Surname)__rejected your request (US[#617 )
7. IF User doesn't have any notifications, the page shall look like the picture 2. 
8. WHEN a new notification occurs, the system shall send push-notification to the User's phone (US[#321](https://github.com/ita-social-projects/Car-Back-End/issues/321)).

**Assumption and Constraints:**
1. Unique journey notification shall be deleted 14 days after the departure time of the journey.
2. Quantity of unread messages (highlighted by light-blue color) shall match with the number indicated in the Notification button of the Footer.
3. System shall block Accept button after the time the ride starts.

**Epic link**
Epic #72 
**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
#2 clarification needed

**Comment by OlenaBobalo** [comment]
> #2 clarification needed

Changed
