### ISSUE TITLE
[Search for Journey] Journey request

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#16]
**As a** User (Passenger) **I want to** create journey requests **so that** system could check it's suitability with newly created journeys or with similar requests of other Users.

**Mockup**
<img width="182" alt="US_20_Your_Car_Initial" src="https://user-images.githubusercontent.com/81674765/114669093-30451680-9d0a-11eb-9293-e3f9516ca756.png">

### Acceptance Criteria
1. User accesses to this screen from Journey Search page (US[#15](https://github.com/ita-social-projects/Car-Back-End/issues/15)) or Search result (US[#13](https://github.com/ita-social-projects/Car-Back-End/issues/13)).
2. Route section should contain the search boxes 'From' and 'To' with addresses entered previously in (US[#12](https://github.com/ita-social-projects/Car-Back-End/issues/12)) .
3. Icon equal to 'Find on the map' should be placed on the right side of the 'From' search box
3.1. WHEN User clicks on 'Find on the map' icon, the system shall navigate to the Map page.
4. 'Departure time' edit box shall show a calendar and a clock for choosing the needed date and time of the trip, same as in (US[#2](https://github.com/ita-social-projects/Car-Back-End/issues/2)).
4.1. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)
5. 'Passengers' dropdown shall contain options '1', '2', '3', '4' seats.
5.1. Option '1' shall be chosen by default.
6. User shall choose Fee mode pushing button 'All' or 'Free' or 'Paid'.
6.1. Button 'All' shall be active by default.
7. Button 'Create Request' (in bold and uppercase) shall send information to trip DB.
7.1. Sent information shall be checked by system each time when new journey is created in the time frame indicated in the request.

**Epic link**
Epic #71 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by zxmiron** [comment]
@OlenaBobalo, please add this user story to some Epic

**Comment by OlenaBobalo** [comment]
> @OlenaBobalo, please add this user story to some Epic

@zxmiron Please read stories from the beginning. On the top is written by capital letters:  STORY ISN'T READY, WHILE DESIGNER DON'T CREATE A NEW VERSION OF MOCK UP.

**Comment by OlenaBobalo** [comment]
@AnnaBalah , please check the mock up. :-) It seems that it wrong - belongs to ride search, but not ride request.
