### ISSUE TITLE
[Manage Messages] Message from passenger

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#17]
**As a** User (Passenger) **I want to** see all Associates who joined the trip **so that** can send one message to all.

**Mockup**
<img width="157" alt="US_17_Message_From_Passenger" src="https://user-images.githubusercontent.com/62544149/99081588-bc240c80-25cb-11eb-9f4a-bc4a7961abe6.png">

### Acceptance Criteria
1. User should assess to this page from exact journey page (US[#4](https://github.com/ita-social-projects/Car-Back-End/issues/4)).
2.  On the top of the page, 3 active buttons shall be available: Back (in blue, at the left, with return sign), Journey (black, at the middle), Leave (orange, at the right) if User/Passenger decides to cancel the agreed trip.
3. Interactive map shows the chosen route.
4. Rolling-up panel should include information about accepted passengers.
4.1. Panel rolls from the bottom to the top by scrolling the black line to the top.
5. Information about the trip organizer should consist of: photo, Name & Surname (N&S), Position at SS, options list (at the right side, marked as "..."), date and time of the journey (under "..." mark, in blue color), Location points.
5. List of passengers accepted by trip organizer should consist of: photo, Name & Surname (N&S), Position at SS.
6. Buttom "Message all" shall transfer User to Message page (US[#22](https://github.com/ita-social-projects/Car-Back-End/issues/22)). 

### Assumption and Constraints:
1. User has access to this page only after User's request is accepted by journey organizer.

**Epic link**
Epic #73 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Vladyslava95** [comment]
The User Story name doesn't match with the content @OlenaBobalo
