### ISSUE TITLE
[Create Journey] Select Date and Time

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#2]
**As a** User **I want to** add date and time of a planned journey **so that** system can notify potential passengers about the journey's exact date and time.

**Mockup**
<img width="180" alt="US_2_CreateJourney_2" src="https://user-images.githubusercontent.com/62544149/102712193-d090ae80-42c7-11eb-952e-a8e2a91bef8b.png">
Pict 2. (Calendar & Clock view)
![US_2_DateTime](https://user-images.githubusercontent.com/62544149/107775792-73562e00-6d49-11eb-925f-0684b0e5bed2.png)

### Acceptance Criteria:
1. User accesses the Date&Time option from Route confirmation page (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).
2. Roll-down edit box "Departure time" shall consist of 2 options (pict.2):
2.1. Calendar. User shall choose a trip date by pushing on the chosen date in the calendar grid.
2.2. Clock. User shall choose the needed time of the trip. Clock shall have a look like in the standard phone alarm clock (00:00).
2.3. Both options shall start from the current moment. Passed date and time shall be disabled.
3. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)

**Epic link**
Epic #67

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

Tasks
 sample task.

**Comment by KERNOR-GENTOR** [comment]
main navigation panel`s been created.
