### ISSUE TITLE
Set up preferences in Profile

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#21]
**As a** User (Driver) **I want to** choose my preferences **so that** potential journey's participants can decide if it will be comfortable for them to join my trip.

**Description**
<img width="166" alt="US_21_Profile_Preferences" src="https://user-images.githubusercontent.com/62544149/100059067-1e360a80-2e33-11eb-8c6d-dce8391071a3.png">

### Acceptance Criteria
1. User assesses to Preferences page from My Profile page (US[#18](https://github.com/ita-social-projects/Car-Back-End/issues/18)), or from Journey Options (US[#46](https://github.com/ita-social-projects/Car-Back-End/issues/46)).
2. User shall push Back button on the top (left corner) of the screen to come back to the previous page.
3. Option "Do you allow smoking in your car?" shall have 2-options scale: Yes and No.
4. Option "Do you allow eating in your car?" shall have 2-options scale: Yes and No.
5. "Comments" edit box shall include a place for manual texting (All kinds of symbols are appropriate).
6. Preferences shall be saved automatically when User leaves the page.

### Assumptions & Constraints
1. "Comments" text box shall contain symbol input limit: 100 symbols. Text: "Up to 100 symbols".

**Epic link**
Epic #65 
**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by VikaUrzan** [comment]
As User I want to see remaining the number of characters in the other preferences
