### ISSUE TITLE
[Choose current User role] Journey Homepage

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#23]
**As** any User **I want to** see the choice of journey options **so that** I can choose search for a journey or create my own journey and list of my existing journeys.

**Mockup**
<img width="174" alt="US_23_Journey_Homepage" src="https://user-images.githubusercontent.com/81674765/114455017-ee21b500-9be3-11eb-9853-f76d57f07767.png">

Picture 2. Navigation pannel (Footer)
<img width="217" alt="US_1_NaviPanel" src="https://user-images.githubusercontent.com/62544149/109803728-12c05f80-7c2a-11eb-99eb-c633e8516144.png">

### Acceptance Criteria
1. User accesses the page by pushing Journey icon on the Footer.
2. Pushing at "Search for ride" image shall move User to "Search for ride" page (US[#12](https://github.com/ita-social-projects/Car-Back-End/issues/12)).
3. Pushing at "Add a ride" image shall move to "Add a ride" page (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).
4. List of agreed trips is described at (US#[11](https://github.com/ita-social-projects/Car-Back-End/issues/11)).
5. Footer contains 4 icons:
5.1. Chats
5.1.1. WHEN User clicks on Chats, the system shall navigate to Chats page (US[#22](https://github.com/ita-social-projects/Car-Back-End/issues/22)).
5.1.2. IF there are unread messages, a red sign with the number of unread messages occurs on the upper right corner of the icon.
5.2. My Profile
5.2.1. WHEN user clicks on My Profile, the system shall navigate to My Profile page  (US[#18](https://github.com/ita-social-projects/Car-Back-End/issues/18)).
5.3. Journey
5.3.1. WHEN user clicks on Journey, the system shall navigate to Journey page
5.3.1.1. IF journey isn't defined yet, systems shall navigate User to "Add a ride" page  (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).
5.3.1.2. IF journey is defined, systems shall navigate User to Journey page (US[#4])
5.4. Event/Notification
5.4.1. WHEN user clicks on  Event, the system shall navigate to  Event page (US[#130]).
5.4.2. IF there are unread notifications, a red sign with the number of unread notifications occurs on the upper right corner of the icon.
6. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)

### Assumption and Constraints:
1. Navigation panel shall be visible when the system navigates to any page.
2. Navigation panel shall be frozen when user scrolls down and up through the initial page.

Epic: #66

**Comment by AnastasiiaDanyliuk** [comment]
It is needed to render information about user journeys, that is given from JourneyController, and to work with scheduled journeys.

**Comment by nrevutska** [comment]
Why the category is "choose current user role"?
