### ISSUE TITLE
[Create Journey] Select route

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#24]
**As** any User **I want to** have options of route choice on the map **so that** could choose the right From/To points of my trip.

**Mockup**
![US_24_Journey_Map_Search](https://user-images.githubusercontent.com/62544149/97699230-7424c600-1ab2-11eb-9767-7127173a7892.png)

Picture 2
<img width="172" alt="US_24_1_Journey_Map_Search" src="https://user-images.githubusercontent.com/62544149/97702593-eea41480-1ab7-11eb-98c9-f5c74c340748.png">

### Acceptance Criteria
1. User accesses to Map Search page, by pushing at the search box at Ride Homepage (US[#23](https://github.com/ita-social-projects/Car-Back-End/issues/23)).
2. System shall open interactive map with User actual location.
2.1. IF the actual location isn't defined, system shall ask User to allow their geolocation.
3. User shall choose their route by 2 ways (pict.2):
3.1. WHEN User pushes at From/To search boxes, a virtual keyboard shall occur at the bottom of the screen (pict. 2).
  3.1.1. User shall manually input addresses of From/To journey points.
  3.1.2. Location indicator shall be placed at the chosen on the map location.
3.2. WHEN User picks up addresses from their address book, which shall be placed under From/To edit box, system should use these addresses for route creation (US#[31](https://github.com/ita-social-projects/Car-Back-End/issues/31)).
3.3 In "Recent journeys" system shall display last 5 unique addresses. This function shall be valid for both From & To options.
3.3.1. IF User used less then 5 addresses, system shall show all previously used addresses.
3.3.2. Shown addresses shouldn't consist of addresses from the User address book (with the same coordinates).
4. WHEN User chooses the needed location on the map, User shall longpress on it and Map's location indicator (blue drop) should occur on the chosen place.
5. Each next Inputted additional stop shall be placed under the previously added stops.
6. IF User decides that the location indicator is on the right place, User shall push "Confirm" button.
6.1. "Confirm" button shall be disabled while boxes To/From are empty (for button enabling both boxes shall be filled).
7. WHEN User pushed Confirm button for both locations From & To, system shall move User to the "Create a Ride" page (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).

### Assumptions & Constraints
1. As rides shall be deleted 14 days after the ride execution, in Recent Rides system shall show only rides for the last 14 days.

**Open Questions:**
1. How system will notify User that geolocation needs to be switched? Is it pop-up window? Isn't it better to inform the User about need for geolocation switching (if it's turned off) directly after the User opens the Application?

**Epic link**
Epic #67 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
Is this story obsolete? How it corresponds to https://github.com/ita-social-projects/Car-Front-End/issues/58?

**Comment by OlenaBobalo** [comment]
@nrevutska As I know it isn't obsolete. I closed 58 (FE), as a clone of 54 (BE).
54 was created on your demand to divide stories into a few smaller. I forgot to delete a part that was moved to a new story. My mistake :-(. I've improved story 24.
