### ISSUE TITLE
[Make Registration] Enter Email

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#244]
**As** any User **I want to** register myself in the application **so that** system can identify me.

**Mock up**:
<img width="158" alt="US_25_Registration" src="https://user-images.githubusercontent.com/62544149/109801410-17cfdf80-7c27-11eb-9377-b4fe335a19a9.png">

### Acceptance Criteria
1. System shall check User's validity through Active Directory function.

### Assumptions & Constraints
1. System shall log User out when User has changed their password for SS Business system.

**Epic link**
Epic ita-social-projects/Car-Back-End#60 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by strelovidniy** [comment]
Outdated story, needs to be updated

**Comment by RuslanPleskun** [comment]
Won't be implemented
