### ISSUE TITLE
[Manage Journey] Journey page (list of journeys)

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#245]
**As** any User **I want to** see all journeys (upcoming, current, and past) **so that** I can find necessary information about all my trips. 

**Mockup**
<img width="126" alt="US_23_Journey_Homepage" src="https://user-images.githubusercontent.com/62544149/136745761-872fbae8-1f26-4767-ae38-df94b96ecc5f.png">
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3306%3A7238

### Acceptance Criteria
1. User shall have access to the list of journeys after pushing Journey icon on the Ride Homepage (US ita-social-projects/Car-Back-End#23 ).
2. On top of list journeys User shall see horizontally scrolled buttons: All, Past, Upcoming, Regular, Requested, Canceled.
3. Each journey should be circled by the line and consist of such information: N&S of journey organizer, SS position, stops addresses during the journey (1st and last stop), time of the ride.
3.1. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)
4. All: system shall show a list of all User's journeys.
4.1 For the All button User shall see on the top Upcoming, then Past, Regular, Requested, Canceled journeys.
5. Upcoming: system shall show a list of upcoming User's journeys only.
6. Past: system shall show a list of past User's journeys only.
6.1. Statistic of past journeys shall be stored in the DB for HR Marketing requests.
7. Regular: system shall show a list of scheduled User's journeys only.
8. Requested: ride requests that were created by passengers.
9. Cancelled: system shall show a list of canceled Users' journeys only.

### Assumptions & Constraints
1. User can scroll up and down the page.
2. Past journeys shall be deleted from the DB 14 days after the journey was fulfilled.
3. Upcoming: all upcoming journeys.
4. Past: journeys that took place during the last 14 days.
5. Cancelled: rides that were canceled during the last 14 days.
5. Ride list shall start from the newest rides (on the top). The older the ride, the lower ride info should be in the list.

**Epic link**
Epic ita-social-projects/Car-Back-End#70 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by YanaRudyi** [comment]
6 not about interaction with user (maybe another story)

**Comment by YanaRudyi** [comment]
3 Upcoming maybe not only 24 hour
4 Past maybe last two weeks

**Comment by VikaUrzan** [comment]
As any Users I want to have ability deleting some of my past journeys

**Comment by VikaUrzan** [comment]
As any Users I don't want to see an ellipsis menu for past journeys

**Comment by ivanstrilchuk** [comment]
Is 3. About list of journeys or journey detailed info screen.
