### ISSUE TITLE
[Manage car info] Add a Car in My Profile

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#33]
**As a** User (Driver) **I want to** input data about my cars **so that** other Users know which car will pick them up.

**Mockup**
<img width="175" alt="US_33_Add-Car" src="https://user-images.githubusercontent.com/81674765/114417362-36c47880-9bba-11eb-9d7f-e018322fe046.png">

### Acceptance Criteria
1. User accesses to My Car profile from initial page of Your car page (US[#20](https://github.com/ita-social-projects/Car-Back-End/issues/20)).
2. WHEN User pushes on Upload Photo button, system shall move User to phone Gallery.
2.1. Image size shall be compressed to 300KB, regardless of the file size.
3. WHEN User pushes on edit boxes "Brand" & "Model" & "Color", system shall show the list of car's brands/models/colors.
3.1. At the top of the list should be the text "Manual input".
3.2. IF User chooses manual input, the virtual keyboard shall roll up from the bottom of the screen.
3.2.1. WHEN User starts to input the first letters, the system shall show all models/brands/colors which contain those letters. 
3.3. Color box shall include 11 colors.
4. Edit box "Plate number" shall be filled by User manually (virtual keypad at the bottom of the screen).
4.1. System shall check Plate Number validity.
4.2. Input symbols shall be limited by 4 categories: numbers, letters, hyphens, space.
4.3. After entering invalid data into the 'Plate number' edit box, the field highlights red and the error message "This field must contain 1-10 characters, including numbers, letters, hyphens, space" appears under the field.
5. Button "Save" shall transfer input info into DB.
6. "Save" button should be disabled until all edit boxes are filled.
7. Mark "star" should be in front of each edit box.
7.1. Text ""star" - required field", should be placed under the "Plate number" box.

**Note**
Data Dictionary

Attribute Name | Definition | Required | Box Type | Format | Field Size | Example
-- | -- | -- | -- | -- | -- | --
Car Photo | Photo of a User's car | N | &nbsp; | image | 300Mb | &nbsp;
Brand | Car brand | Y | drop-down | text | 2-20 | Chevrolet Corvet
Model | Car model | Y | drop-down | text | 2-20 | Tiguan
Color | Car color | Y | drop-down | text | 3-6 | white, black,   grey, blue, red, yellow, green, brown, beige, violet, orange
Plate Number | Registration number | Y | edit | text, number, hyphen, space | 1-10 | XG-SF-67; 8

**Epic link**
Epic #62

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by SashaOsypova** [comment]
https://github.com/ita-social-projects/Car-Front-End/issues/416#issue-899107294

**Comment by SashaOsypova** [comment]
#https://github.com/ita-social-projects/Car-Front-End/issues/410#issue-896510750

**Comment by SashaOsypova** [comment]
[https://github.com/ita-social-projects/Car-Front-End/issues/410#issue-896510750](url)

**Comment by SashaOsypova** [comment]
Bug for this story: https://github.com/ita-social-projects/Car-Front-End/issues/410#issue-896510750

**Comment by SashaOsypova** [comment]
Bug for this story: https://github.com/ita-social-projects/Car-Front-End/issues/416#issue-899107294
