### ISSUE TITLE
[Manage car info] More options > Remove a car

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#37]
**As a** User (Driver) **I want to** have the possibility to delete information about my car **so that** I could remove invalid information.

**Mockup**
<img width="252" alt="US_36_Add-Car_Option_2" src="https://user-images.githubusercontent.com/62544149/99675845-62668b00-2a80-11eb-9f2f-ce73075c92c8.png">

### Acceptance Criteria
1. User assesses to More Options panel from Edit Car page (US[#53](https://github.com/ita-social-projects/Car-Back-End/issues/53)).
2. Pushing at "Remove a car" opens a pop-up window: "Are you sure you want to delete your car information?" with two possible variants: "Yes, delete it" and "No, keep it". 
3. Pushing at "Yes, delete it" shall delete User's car from the DB and transfer User to Your Cars page.

**Epic link**
Epic #62  

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
Replace ellipsis with Remove button

**Comment by OlenaBobalo** [comment]
@nrevutska Remove ellipsis? we don't have ellipsis here...
