### ISSUE TITLE
[Manage Journey] Journey

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#4]
**As** any User **I want to** see the route on the map and passengers details **so that** I could plan my trip.

**Mockup**
Driver Case
![US_3_2_Journey](https://user-images.githubusercontent.com/62544149/111752183-0b41bd00-889e-11eb-9efb-5fa44f3ab98c.png)
Passenger Case
<img width="157" alt="US_17_Message_From_Passenger" src="https://user-images.githubusercontent.com/62544149/113107587-c78b7380-920c-11eb-99b7-a3158bda4bb7.png">
![image](https://user-images.githubusercontent.com/62544149/139019071-c6512450-8167-4f4f-87c9-937a24a84113.png)
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=4086%3A14806
All User Case
<img width="217" alt="US_3_3_Journey" src="https://user-images.githubusercontent.com/62544149/111949741-ed689800-8ae9-11eb-8ecc-fbb5ee10fdf8.png">

### Acceptance Criteria
1. User has access to the Journey page in 2 ways:
1.1. User chooses unique journey at Journey Homepage (US[#23  ].
1.2. System automatically switches the screen to Journey after the creation of the trip (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).
2. Active buttons shall be available: Back (return to the previous page),
2.1. IF User is Driver, the system shall show Elipsis menu: Edit the Ride Route (US #910  ), Edit the Ride (US #9 ), Cancel the Ride.
2.2. IF User is Passenger, the system shall show Leave button (if User decides to leave this journey) (US[#459](https://github.com/ita-social-projects/Car-Back-End/issues/459)).
2.2.1. IF User pushes Leave button, the system shall open a pop up with question "Do you really want to leave the journey?" with the buttons "Yes, leave" and "No, stay".
2.2.1.1. IF User pushes "Yes" button, the system shall send notification to Driver (US[#459](https://github.com/ita-social-projects/Car-Back-End/issues/459)) and delete User from the list of passengers for that ride.
2.2.1.2 IF User pushes "No" button, the system shall close pop up.
3. Car info shall consist of Car photo (from US[#20 ), brand, model, color; (in new line) plate number.
4. All location points shall be present. 
4.1. WHEN any of the location stop corresponds to the current User's stop, the system notifies about it by the sign "Your Stop" in the same line where the passenger's location stop is written.
5. Rolling-up panel should include information about potential passengers.
5.1. Panel rolls from the bottom to the top by scrolling the black line to the top (pict.3).
6. List of passengers who applied/approved for a journey should consist of: Name & Surname (N&S), Position at SS, time and date of journey (in blue), 
7. Under the text SOFTSERVIANS, the list of SS associates who request to join the trip shall be present.
8. WHEN User pushes on the Associate's N&S mark, system shall transfer User to the passenger profile (US[#313](https://github.com/ita-social-projects/Car-Back-End/issues/313)).
9. Button "Message All" shall be locked at the bottom of the pop-up panel.
9.1. WHEN User pushes "Message all", the system shall transfer User to Chat page (US[#45](https://github.com/ita-social-projects/Car-Back-End/issues/45)).
10. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376).

### Assumptions & Constraints
1. Elipsis Menu shall not be valid for past trips.
2. Driver and passenger stopping points, which are within 500 meters of each other, must be intertwined and displayed as one stop in the application.

**Epic link**
Epic #70 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
#6 need to clarify and verify the story link
