### ISSUE TITLE
[Manage Address Book] More options

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#43]
**As** any User **I want to** use addresses additional options **so that** I can moderate existing information.

**Description**
![US_43_Address_Book_Options](https://user-images.githubusercontent.com/62544149/109983042-22fc3b80-7d0b-11eb-80a6-ac349e3a63f3.png)

### Acceptance Criteria
1. User assesses to More Options panel from Edit Address page (US[#303](https://github.com/ita-social-projects/Car-Back-End/issues/303)).
2.WHEN User pushes "Remove the address", system shall open a pop-up window with two options: "Yes, delete it" and "No, keep it".
4.1. IF User chooses Yes, delete it, system shall delete all information about the chosen address and transfer User to Address book page (US #31 )
4.2. IF User chooses No, keep it, system shall transfer User to the current Edit Address page.

**Epic link**
Epic #63 

**Open Questions**
1. Do we really need these functions???

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
Need to remove this story

**Comment by OlenaBobalo** [comment]
Agree! :-)
