### ISSUE TITLE
[Manage Address Book] Add Address

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#44]
**As** any User **I want to** add addresses to my Address book **so that** I save my time during inputting often used addresses on App pages.
 
**Mockups**
<img width="507" alt="US_44__Add_Address" src="https://user-images.githubusercontent.com/62544149/109656666-56a15f00-7b6d-11eb-99fd-4174439b7d40.png">

### Acceptance Criteria
1. User accesses to Add Address page by pushing:
1.1. at "Address book" page during User initial visit of Address Book page (US[#31](https://github.com/ita-social-projects/Car-Back-End/issues/31)).
2. System shall open an interactive map with User actual location.
3. User shall choose a necessary location by using 2 options:
3.1. WHEN the User chooses the needed location on the map, the User shall push on it and Map's location indicator (drop) should occur on the chosen place.
3.2. WHEN the User pushes the Address box, a virtual keyboard shall occur at the bottom of the screen (pict. 2).
3.2.1. User shall manually input addresses of points.
3.2.2. Location indicator (drop) shall be placed at the chosen on the map location.
3.3. When User pushes "x" mark at the right of the edit box, the system shall delete chosen address.
4. Edit box "Name the chosen address" shall be present under the Address box.
4.1. IF User doesn't fill "Name the chosen address" edit box, the system shall automatically save the address as a name.
5. Edit box "Choose the type of the Address name and the icon" shall be present under the"Name the chosen address".
5.1. Address name shall consist of Home (icon of the house), Work (icon of the bag), Other (star icon).
5.2. IF User doesn't choose the address type, the system shall automatically choose the type Other.
6. IF the User decided that the location indicator is in the right place, the User shall push "Save" button.
7. WHEN User pushed Save button, the system shall move the User to the "Address book" page (US[#31](https://github.com/ita-social-projects/Car-Back-End/issues/31)) and place chosen address, name, and icon in the Address book list  (US[#31](https://github.com/ita-social-projects/Car-Back-End/issues/31)).

**Epic link**
Epic #63 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Vladyslava95** [comment]
@OlenaBobalo Could we add max number of characters to enter into the "Address"," Name the chosen address" ?
