### ISSUE TITLE
[Manage Messages] Write in journey chat

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#45]
**As any** User **I want to** chat with people related to the journeys **so that** we can send immediate messages to each other.

**Mockup**
<img width="514" alt="update #45" src="https://user-images.githubusercontent.com/78938450/113129868-11cc1f00-9224-11eb-9397-630f677d3433.png">

### Acceptance Criteria
1. User accesses to this page from Messages page (US[#22 ](https://github.com/ita-social-projects/Car-Back-End/issues/22)) or pushing "Message all" at pages Journey (US[#4](https://github.com/ita-social-projects/Car-Back-End/issues/4)).
2. WHEN User types a text and pushes "Send a message", system shall send a message to all Users who participate in the unique journey.
3. Unique journey's chat shall be created only after the message creation by any User User participating in that journey.
4. User can scroll up and down the page.
4.1. WHEN the user scrolls up, the button Return to the Buttom is shown.
5. Each Message in a unique chat shall contain the date and time of the message sending in the right down corner of the message.
5.1. The date format: DD.MM
5.2. The time format: 00:00
6. System shall let the User copy sent messages and paste them to message box.

### Assumptions & Constraints
1. Text box shall contain a symbol input limit: 500 symbols.
2. Button "Send a message" shall be deactivated while the text box is empty.
3. Chat messages shall take up to 80% of the row place if text space is more than 1 line long.
4. Initial size of the text box shall consist of 1 line, but it shall increase to 6 lines, depending on symbols' quantity.
5.  Message list shall start from the newest message (on the top). The older the message, the lower it should be in the list.

**Epic link**
Epic #73  

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Vladyslava95** [comment]
@OlenaBobalo  We have a constraint that "Chat shall be deleted 24 hours after the departure time of the journey.", but the same we have at story 22. This info should be present in both US or not?
