### ISSUE TITLE
[Manage Messages] Search in Messages

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#46]
**As any** User **I want to** have search functionality,  **so that** can find needed information not losing time for browsing through all messages pages.

**Mockup**
![US_46_Message_Search](https://user-images.githubusercontent.com/62544149/113158972-ead21500-9244-11eb-951a-6f0b2bc11e85.png)
![US_46_1_Message_Search](https://user-images.githubusercontent.com/62544149/113158801-c4ac7500-9244-11eb-9a65-b9ea19c72b43.png)
<img width="151" alt="US_46_2_Message_Search" src="https://user-images.githubusercontent.com/62544149/113159136-0b9a6a80-9245-11eb-9244-2599f7260175.png">

If nothing had found:
<img width="179" alt="US_46_Message_Search_1" src="https://user-images.githubusercontent.com/62544149/110950774-ef459500-834c-11eb-8137-fbf7f3234464.png">

### Acceptance Criteria
1. User accesses this page from Chats page (US[#22](https://github.com/ita-social-projects/Car-Back-End/issues/22)).
2. User should be able to see searched content updated in real-time as they type until no further coincidences found. 
3. IF no coincidences found, the message shall be displayed: No results matching your search filters.
4. The system should search words in:
a. Titles
b. Content.
5. All search results should be placed in a vertical row in the order of newest chats > oldest chats.
6. Cross mark for deleting text in the search box shall be available on the right side of the search box.
7. Requirements to date and time appearance are given in US[#376](https://github.com/ita-social-projects/Car-Back-End/issues/376)

### Assumption and Constraints:
1. Text box shall contain a symbol input limit: 25 symbols.
2. Search shall start after entering more than 2 symbols.

**Epic link**
Epic #73  

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Vladyslava95** [comment]
@OlenaBobalo At the Assumption and Constraints are written that "Search shall start after entering more than 2 symbols", but at the meeting, we discussed that Search shall start after 3 symbols

**Comment by OlenaBobalo** [comment]
> @OlenaBobalo At the Assumption and Constraints are written that "Search shall start after entering more than 2 symbols", but at the meeting, we discussed that Search shall start after 3 symbols

@Vladyslava95 "start after 3 symbols" means that the search will start from the 4th symbol. :-)
As I remember we agreed that the search starts from the 3rd symbol. Don't we?

**Comment by Vladyslava95** [comment]
> > @OlenaBobalo At the Assumption and Constraints are written that "Search shall start after entering more than 2 symbols", but at the meeting, we discussed that Search shall start after 3 symbols
> 
> @Vladyslava95 "start after 3 symbols" means that the search will start from the 4th symbol. :-)
> As I remember we agreed that the search starts from the 3rd symbol. Don't we?

@OlenaBobalo  oh, I got it. Yeap, the search starts from the 3rd symbol)))) Thx)

**Comment by Vladyslava95** [comment]
@OlenaBobalo There is a text "Team shall decide which search approach to use."  under the second point. What does it mean? What does the additional approach team need to choose?)

**Comment by YuriiDanyliv** [comment]
Not implemented focusing on searched text
