### ISSUE TITLE
[Manage Joiners] New Applicant page

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#5]
**As a** User (Driver) **I want to** see potential passenger details and requests **so that** I could decide to accept or decline it.

**Mockup**
<img width="437" alt="US_5_Accept_Request" src="https://user-images.githubusercontent.com/62544149/118236552-e41efa80-b49e-11eb-9a66-45231884d155.png">

### Acceptance Criteria
1. Page of New Applicant occurs after User actions on Notification page (US[#6](https://github.com/ita-social-projects/Car-Back-End/issues/6)).
2. On the top of the window 2 marks are available: text "New Applicant" (static) and "Back" (let to come back to the previous screen).
3. Applicant's personal data should consist of: applicant's photo, Name & Surname (N&S), SS position, the number of previous rides through App, badges.
4. IF Applicant wrote any comments during proceeding with this application, the system should show it in the Box under Applicants details (US [#14 ]).
5. Options for baggage should be: Applicant choice (US[#12 ]).
6. List of stops should demonstrate all necessary stops starting from User departure from the first point and till the last User stop.
7. Applicant's stops shall be highlighted in blue and User should have a possibility to view them on the map.
7.1. All stops of the route shall be shown of the map.
8. Two buttons "Accept" and "Decline" shall be on the bottom of the window.
9. Chosen button should change its color to black.
9.1. IF User pushes Accept button, system shall send a notification to the User: Your trip request is approved (US[#416 ]).
9.2. IF User pushes Decline button, system shall send a notification to the User: Your trip request is declined.

**Assumption and Constraints:**
1. Notification shall be deleted from the Notification list after User taps Decline or Accept button (to avoid sending multiple notifications).

**Epic link**
Epic #68 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
Need to add a story about the view on the map

**Comment by nrevutska** [comment]
Let`s not use gradient in blue text (stops block)

**Comment by OlenaBobalo** [comment]
> Let`s not use gradient in blue text (stops block)

Agree
