### ISSUE TITLE
Journey Change

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Back-End#9]
**As a** User (Driver) **I want to** have the possibility to make changes in my previously created journey **so that** my passengers were aware of changes.

**Mockup**
<img width="311" alt="US_9_Change_Journey" src="https://user-images.githubusercontent.com/62544149/110787638-44fb3e00-8276-11eb-9c64-d28f74822ef3.png">

### Acceptance Criteria
1. User accesses "Edit the journey" after pushing Edit on Journey page (US[#4](https://github.com/ita-social-projects/Car-Back-End/issues/4)). ???
2. Scrolling list of edit boxes on the page should contain From-To boxes, Departure time, Journey type, Choose a car, Available seats, Free-Paid function, Comments, Scheduled Journey and Invited Softservians.
3. All boxes mentioned above, shall be the same as on Create Journey page (US[#3](https://github.com/ita-social-projects/Car-Back-End/issues/3)).
4. At the bottom of the page, 2 options should be available: Discard Journey and Apply Changes.
5. IF User pushes the Discard Journey button, the pop-up window shall occur.
5.1.  IF User chooses "Yes, discard", the system shall refuse all changes made on this page and transfer User to the previous page.
5.2.  IF User chooses "No, keep it", the system shall close the pop-up window and leave User on the same page.
6. IF User pushes an Apply Changes button, the pop-up window shall occur (US[#10](https://github.com/ita-social-projects/Car-Back-End/issues/10)).

### Assumptions & Constraints
1. User could make changes only to previously created journeys and journeys which User didn't fulfill yet.
2. The number of free places  shall not be less than already applied passengers.
3. Search/"Comments" text boxes shall contain symbol input limit: 100 symbols. Text: "Up to 100 symbols".

**Epic link**
Epic #70 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
Need to send a notification when journey is changed

**Comment by nrevutska** [comment]
Add restriction regarding the count of free places (not less than already applied passengers)
